# Generated by Django 4.1.1 on 2022-09-06 09:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="created",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
